### ISSUE TITLE
Indentation in application/metadata.js needs fixing up

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/community-apps#7]
- `[` should be on its own line, indented 4 spaces.
- Subsequent objects etc. should be indented in multiples of 4 spaces.

**Comment by AleziaKurdis** [comment]
Addressed in PR #27
I fixed the metadata generator and then used it to generate the last version of the metadata.js file.

**Comment by JulianGro** [comment]
This should be fixed with PR #27
